Repository pytest-dev/pytest-xprocess, pull requests merged in 2020-10, with the labels that each got.

#42 Use cache.makedir instead of dot-directory
  CHANGELOG.rst
  pytest_xprocess.py
Labels: enhancement

#43 Release 0.15.0
  CHANGELOG.rst
Labels: release

#45 Add CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: docs

#46 Move requirements to setup.py
  setup.cfg
  setup.py
Labels: docs

#44 add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  issue_template.md
Labels: docs

#48 Add section on potential problems related to stream buffering to README.md
  README.rst
Labels: docs

#23 Detect process termination during execution
  CHANGELOG.rst
  example/server.py
  example/test_server.py
  xprocess.py
Labels: enhancement, waiting

#50 Refactor zombie process test into two tests
  example/test_server.py
Labels: enhancement, test suite

#21 Easier to extend max lines read
  CHANGELOG.rst
  README.rst
  example/server.py
  example/test_server.py
  xprocess.py
Labels: enhancement, waiting

#52 configurable timeout for process starter
  CHANGELOG.rst
  README.rst
  example/server.py
  example/test_server.py
  xprocess.py
Labels: enhancement

#53 release 0.16.0
  CHANGELOG.rst
  README.rst
Labels: release
